language: java
jdk:
- openjdk11
dist: trusty
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku:git
  app: library-loan-api
  api_key:
    secure: LC3ZHhGCyplAWKyZCD97I/Eg9BocxjgE9lW6JYHEKmSzW+KrJx81gJWrSu2LcWEDayyAMcO0jpduz9b8CZONAD0+h7Hez/nkAsecH/NpCGQJE8J5ZL84s5FeitDmvbtZgsTPN+0qZobc4PGddXi1Wg5sIEkJaHJkDRGEwwqPZlmuhhmf1+BQ59tIeV0CGhqr+752HvktZPcRItZ7Gzqz46a4coaREFTZDbOvPbdjoFKHXs1qKWj51pvs65+BYiZrAgZMPtwaXk5/xJ/sh7y9RkuCupnY9e9o5ZC2KL5w/00XldjVoRQUWDNYjDDuCX2jMByyZZapKZ/j1anpKUP73gj2HwjWUcSsY/FNlVNSqM6gqjRnqtRrQNk3qpC4n7eLf0H6CIbbSKRnsVezYyNz6/glfLVP1hsDr69q5N9zGFZsi+yu9lu6DuhyEC+y67xVFEwOnO+4pTQrNToiYtJKEopeKhZYC/NnmJ75WQs6IuZPv71HH74vWAuX2Lar3ZeTjWIsSzQfpmjmDzHy9fmwoJ6mbJ7GbCaDy01h0DwwzLygUBdsfvCXvy7XF3gEi3ib3OcwmVyHAr/iBWf30fNB1E4k2WhMYfbXF+Ehb4+Y4abdVMs6+l5NLHLSlzUjJamFjbtzgazV3vkU8XV3pcOviTNfv9TmhvP10xVMBzlQ2rI=
  edge: true
  on:
    branch: master
